### ISSUE TITLE
resolveExtension Esbuild config

### ISSUE THREAD

**Issue by dalcib** [hanayashiki/esbuild-rn#1]
Very interesting project.

Maybe the [resolveExtension](https://esbuild.github.io/api/#resolve-extensions) Esbuild config option can help to simplify the code.
With this option the server code could be written in this way:

```javascript
...
app.get('/index.bundle', async (req, res) => {
  const platform = req.query!.platform

  const result = await build({
      stdin: {
        contents: stdinContent,
        resolveDir: '.',
        sourcefile: 'stdin.js',
        loader: 'js',
      },
      outdir: 'play/build',
      bundle: true,
      plugins: [
        createFlowStripTypePlugin(/node_modules[/|\\]react-native.*\.jsx?$/g),
        //rnResolvePlugin,
      ],
      loader: {
        '.png': 'file',
        '.jpg': 'file',
      },
      banner: {
        js: banner,
      },
      resolveExtensions: [
        `.${platform}.tsx`,
        `.${platform}.ts`,
        `.${platform}.jsx`,
        `.${platform}.js`,
        '.native.tsx',
        '.native.ts',
        '.native.jsx',
        '.native.js',
        '.tsx',
        '.ts',
        '.jsx',
        '.js',
      ],
    })
  
    res.setHeader('content-type', 'application/javascript')
    res.sendFile(path.join(__dirname, './build/stdin.js'))
  })
...

```

**Comment by hanayashiki** [comment]
> Very interesting project.
> 
> Maybe the [resolveExtension](https://esbuild.github.io/api/#resolve-extensions) Esbuild config option can help to simplify the code.
> With this option the server code could be written in this way:
> 
> ```js
> ...
> app.get('/index.bundle', async (req, res) => {
>   const platform = req.query!.platform
> 
>   const result = await build({
>       stdin: {
>         contents: stdinContent,
>         resolveDir: '.',
>         sourcefile: 'stdin.js',
>         loader: 'js',
>       },
>       outdir: 'play/build',
>       bundle: true,
>       plugins: [
>         createFlowStripTypePlugin(/node_modules[/|\\]react-native.*\.jsx?$/g),
>         //rnResolvePlugin,
>       ],
>       loader: {
>         '.png': 'file',
>         '.jpg': 'file',
>       },
>       banner: {
>         js: banner,
>       },
>       resolveExtensions: [
>         `.${platform}.tsx`,
>         `.${platform}.ts`,
>         `.${platform}.jsx`,
>         `.${platform}.js`,
>         '.native.tsx',
>         '.native.ts',
>         '.native.jsx',
>         '.native.js',
>         '.tsx',
>         '.ts',
>         '.jsx',
>         '.js',
>       ],
>     })
>   
>     res.setHeader('content-type', 'application/javascript')
>     res.sendFile(path.join(__dirname, './build/stdin.js'))
>   })
> ...
> ```

doesn't always work.

You need to prioritize .android.js when you are resolving from an .android.js (which could happen on a iOS compilation too).

**Comment by hanayashiki** [comment]
thank you for your interest in this project!
